name: Scrape FSD Data

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  scrape_fsd:
    name: Scrape FSD Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python fsd_scrape.py

      - name: Start FastAPI server
        run: uvicorn app:app --host 0.0.0.0 --port 8000 --reload &

      - name: Wait for FastAPI server to start
        run: |
          sleep 5
          curl --retry 10 --retry-connrefused http://localhost:8000/scraped_data

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update scraped data [skip ci]"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@users.noreply.github.com"
